-- 创建超级管理员
INSERT INTO OA_USER(ID,NAME,LOGIN_NAME,PASSWORD,DEPARTMENT_ID) VALUES (1,'系统管理员','admin','81dc9bdb52d04dc20036dbd8313ed055',NULL);
-- 初始化权限
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (1,'系统管理',NULL,NULL);
-- 用户管理
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (2,'用户管理','/user/list',1);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (20,'用户列表','/user/list',2);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (21,'用户添加','/user/add',2);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (22,'用户删除','/user/delete',2);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (23,'用户修改','/user/edit',2);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (24,'初始化密码','/user/initPassword',2);
-- 岗位管理
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (3,'岗位管理','/role/list',1);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (30,'岗位列表','/role/list',3);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (31,'岗位添加','/role/add',3);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (32,'岗位删除','/role/delete',3);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (33,'岗位修改','/role/edit',3);
-- 部门管理
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (4,'部门管理','/department/list',1);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (40,'部门列表','/department/list',4);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (41,'部门添加','/department/add',4);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (42,'部门删除','/department/delete',4);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (43,'部门修改','/department/edit',4);

-- 网上交流
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (5,'网上交流',NULL,NULL);

-- 论坛管理
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (51,'论坛管理','/forum/list',5);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (52,'论坛列表','/forum/list',51);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (53,'论坛添加','/forum/add',51);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (54,'论坛删除','/forum/delete',51);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (55,'论坛修改','/forum/edit',51);
INSERT INTO OA_PRIVILEGE (ID,NAME,URL,PARENT_ID) VALUES (56,'论坛移动','/forum/move',51);


